// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: services/rng-service/rng.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RNGRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // Number of random integers requested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RNGRequest) Reset() {
	*x = RNGRequest{}
	mi := &file_services_rng_service_rng_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RNGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RNGRequest) ProtoMessage() {}

func (x *RNGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_rng_service_rng_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RNGRequest.ProtoReflect.Descriptor instead.
func (*RNGRequest) Descriptor() ([]byte, []int) {
	return file_services_rng_service_rng_proto_rawDescGZIP(), []int{0}
}

func (x *RNGRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RNGResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Numbers       []int64                `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"` // The sequence of random numbers (stop indices)
	Seed          string                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`               // The current seed used for audibility
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RNGResponse) Reset() {
	*x = RNGResponse{}
	mi := &file_services_rng_service_rng_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RNGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RNGResponse) ProtoMessage() {}

func (x *RNGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_rng_service_rng_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RNGResponse.ProtoReflect.Descriptor instead.
func (*RNGResponse) Descriptor() ([]byte, []int) {
	return file_services_rng_service_rng_proto_rawDescGZIP(), []int{1}
}

func (x *RNGResponse) GetNumbers() []int64 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *RNGResponse) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

var File_services_rng_service_rng_proto protoreflect.FileDescriptor

const file_services_rng_service_rng_proto_rawDesc = "" +
	"\n" +
	"\x1eservices/rng-service/rng.proto\x12\x03rng\"\"\n" +
	"\n" +
	"RNGRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\";\n" +
	"\vRNGResponse\x12\x18\n" +
	"\anumbers\x18\x01 \x03(\x03R\anumbers\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\tR\x04seed2<\n" +
	"\x03RNG\x125\n" +
	"\x10GetRandomNumbers\x12\x0f.rng.RNGRequest\x1a\x10.rng.RNGResponseB?Z=github.com/ShadyDevelopment/ECHOBETZ/services/rng-service;rngb\x06proto3"

var (
	file_services_rng_service_rng_proto_rawDescOnce sync.Once
	file_services_rng_service_rng_proto_rawDescData []byte
)

func file_services_rng_service_rng_proto_rawDescGZIP() []byte {
	file_services_rng_service_rng_proto_rawDescOnce.Do(func() {
		file_services_rng_service_rng_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_rng_service_rng_proto_rawDesc), len(file_services_rng_service_rng_proto_rawDesc)))
	})
	return file_services_rng_service_rng_proto_rawDescData
}

var file_services_rng_service_rng_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_rng_service_rng_proto_goTypes = []any{
	(*RNGRequest)(nil),  // 0: rng.RNGRequest
	(*RNGResponse)(nil), // 1: rng.RNGResponse
}
var file_services_rng_service_rng_proto_depIdxs = []int32{
	0, // 0: rng.RNG.GetRandomNumbers:input_type -> rng.RNGRequest
	1, // 1: rng.RNG.GetRandomNumbers:output_type -> rng.RNGResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_rng_service_rng_proto_init() }
func file_services_rng_service_rng_proto_init() {
	if File_services_rng_service_rng_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_rng_service_rng_proto_rawDesc), len(file_services_rng_service_rng_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_rng_service_rng_proto_goTypes,
		DependencyIndexes: file_services_rng_service_rng_proto_depIdxs,
		MessageInfos:      file_services_rng_service_rng_proto_msgTypes,
	}.Build()
	File_services_rng_service_rng_proto = out.File
	file_services_rng_service_rng_proto_goTypes = nil
	file_services_rng_service_rng_proto_depIdxs = nil
}
