// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: services/rng-service/rng.proto

package rng

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RNG_GetRandomNumbers_FullMethodName = "/rng.RNG/GetRandomNumbers"
)

// RNGClient is the client API for RNG service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RNGClient interface {
	GetRandomNumbers(ctx context.Context, in *RNGRequest, opts ...grpc.CallOption) (*RNGResponse, error)
}

type rNGClient struct {
	cc grpc.ClientConnInterface
}

func NewRNGClient(cc grpc.ClientConnInterface) RNGClient {
	return &rNGClient{cc}
}

func (c *rNGClient) GetRandomNumbers(ctx context.Context, in *RNGRequest, opts ...grpc.CallOption) (*RNGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RNGResponse)
	err := c.cc.Invoke(ctx, RNG_GetRandomNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RNGServer is the server API for RNG service.
// All implementations must embed UnimplementedRNGServer
// for forward compatibility.
type RNGServer interface {
	GetRandomNumbers(context.Context, *RNGRequest) (*RNGResponse, error)
	mustEmbedUnimplementedRNGServer()
}

// UnimplementedRNGServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRNGServer struct{}

func (UnimplementedRNGServer) GetRandomNumbers(context.Context, *RNGRequest) (*RNGResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRandomNumbers not implemented")
}
func (UnimplementedRNGServer) mustEmbedUnimplementedRNGServer() {}
func (UnimplementedRNGServer) testEmbeddedByValue()             {}

// UnsafeRNGServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RNGServer will
// result in compilation errors.
type UnsafeRNGServer interface {
	mustEmbedUnimplementedRNGServer()
}

func RegisterRNGServer(s grpc.ServiceRegistrar, srv RNGServer) {
	// If the following call panics, it indicates UnimplementedRNGServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RNG_ServiceDesc, srv)
}

func _RNG_GetRandomNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RNGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RNGServer).GetRandomNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RNG_GetRandomNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RNGServer).GetRandomNumbers(ctx, req.(*RNGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RNG_ServiceDesc is the grpc.ServiceDesc for RNG service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RNG_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rng.RNG",
	HandlerType: (*RNGServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomNumbers",
			Handler:    _RNG_GetRandomNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/rng-service/rng.proto",
}
