// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: services/rng-service/proto/rng.proto

package rng

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RNGService_GetNumbers_FullMethodName = "/rng.RNGService/GetNumbers"
)

// RNGServiceClient is the client API for RNGService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RNGServiceClient interface {
	GetNumbers(ctx context.Context, in *RNGRequest, opts ...grpc.CallOption) (*RNGResponse, error)
}

type rNGServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRNGServiceClient(cc grpc.ClientConnInterface) RNGServiceClient {
	return &rNGServiceClient{cc}
}

func (c *rNGServiceClient) GetNumbers(ctx context.Context, in *RNGRequest, opts ...grpc.CallOption) (*RNGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RNGResponse)
	err := c.cc.Invoke(ctx, RNGService_GetNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RNGServiceServer is the server API for RNGService service.
// All implementations must embed UnimplementedRNGServiceServer
// for forward compatibility.
type RNGServiceServer interface {
	GetNumbers(context.Context, *RNGRequest) (*RNGResponse, error)
	mustEmbedUnimplementedRNGServiceServer()
}

// UnimplementedRNGServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRNGServiceServer struct{}

func (UnimplementedRNGServiceServer) GetNumbers(context.Context, *RNGRequest) (*RNGResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNumbers not implemented")
}
func (UnimplementedRNGServiceServer) mustEmbedUnimplementedRNGServiceServer() {}
func (UnimplementedRNGServiceServer) testEmbeddedByValue()                    {}

// UnsafeRNGServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RNGServiceServer will
// result in compilation errors.
type UnsafeRNGServiceServer interface {
	mustEmbedUnimplementedRNGServiceServer()
}

func RegisterRNGServiceServer(s grpc.ServiceRegistrar, srv RNGServiceServer) {
	// If the following call panics, it indicates UnimplementedRNGServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RNGService_ServiceDesc, srv)
}

func _RNGService_GetNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RNGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RNGServiceServer).GetNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RNGService_GetNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RNGServiceServer).GetNumbers(ctx, req.(*RNGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RNGService_ServiceDesc is the grpc.ServiceDesc for RNGService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RNGService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rng.RNGService",
	HandlerType: (*RNGServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNumbers",
			Handler:    _RNGService_GetNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/rng-service/proto/rng.proto",
}
