// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: services/game-engine-service/proto/engine.proto

package engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameEngine_Spin_FullMethodName = "/engine.GameEngine/Spin"
)

// GameEngineClient is the client API for GameEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameEngineClient interface {
	Spin(ctx context.Context, in *SpinRequest, opts ...grpc.CallOption) (*SpinResponse, error)
}

type gameEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewGameEngineClient(cc grpc.ClientConnInterface) GameEngineClient {
	return &gameEngineClient{cc}
}

func (c *gameEngineClient) Spin(ctx context.Context, in *SpinRequest, opts ...grpc.CallOption) (*SpinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpinResponse)
	err := c.cc.Invoke(ctx, GameEngine_Spin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameEngineServer is the server API for GameEngine service.
// All implementations must embed UnimplementedGameEngineServer
// for forward compatibility.
type GameEngineServer interface {
	Spin(context.Context, *SpinRequest) (*SpinResponse, error)
	mustEmbedUnimplementedGameEngineServer()
}

// UnimplementedGameEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameEngineServer struct{}

func (UnimplementedGameEngineServer) Spin(context.Context, *SpinRequest) (*SpinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Spin not implemented")
}
func (UnimplementedGameEngineServer) mustEmbedUnimplementedGameEngineServer() {}
func (UnimplementedGameEngineServer) testEmbeddedByValue()                    {}

// UnsafeGameEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameEngineServer will
// result in compilation errors.
type UnsafeGameEngineServer interface {
	mustEmbedUnimplementedGameEngineServer()
}

func RegisterGameEngineServer(s grpc.ServiceRegistrar, srv GameEngineServer) {
	// If the following call panics, it indicates UnimplementedGameEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameEngine_ServiceDesc, srv)
}

func _GameEngine_Spin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameEngineServer).Spin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameEngine_Spin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameEngineServer).Spin(ctx, req.(*SpinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameEngine_ServiceDesc is the grpc.ServiceDesc for GameEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.GameEngine",
	HandlerType: (*GameEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Spin",
			Handler:    _GameEngine_Spin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/game-engine-service/proto/engine.proto",
}
